Export table tickets
julianMondragon/TAS360 pull request #35
Opened 2024-08-30 15:32 UTC by DulceAPTS

Se agregó el método exportar tabla tickets en Tickets Controller que crea un archivo de Excel con una tabla de los tickets que hay en el índice y en el índice con filtro(s) aplicado(s), con sus respectivos botones de exportar en las vistas Index e IndexWithFilter. Se hicieron modificaciones en los métodos Index e IndexWithFilter dentro de Tickets Controller para llenar la lista de tickets que se sobreescribe en el archivo de excel de la tabla prototipo, se modificó el nombre para evitar la repetición de ".xlsx".

2024-08-31 05:25 UTC, julianMondragon commented on Controllers/TicketsController.cs
> +            // Construye el nombre del archivo sin repetir ".xlsx"
Remueve los comentarios de chatGPT

2024-08-31 05:29 UTC, julianMondragon commented on Models/ViewModel/TicketViewModel.cs
>          public List<CurrentList2> CurrentList2 { get; set; }
¿Currentlist2 se usa?
realiza pruebas en los metodos de ticket (CRUD + ) donde si eliminas la variable que comportamiento tiene su ausencia.

2024-08-31 05:39 UTC, julianMondragon commented on Controllers/TicketsController.cs
> +            if (!Directory.Exists(savePath))
aqui tienes un bug. 

cada dia tendras un archivo por usuario guardado en el servidor. 
esto algun día puede llenar el almancenamiento de la unidad donde se alamacena el proyecto.

anexo evidencia: 

![image](https://github.com/user-attachments/assets/e1fb14c9-5192-4d65-bedc-68d10fd3a1f3)

2024-08-31 05:45 UTC, julianMondragon commented on Controllers/TicketsController.cs
> +        public FileResult ExportTableTickets(string encodedCurrentList)
El metodo ExportTableTickets no tiene su decorador para autenticar al usuario. 
Con esto cualquier persona que tenga acceso a tickets podrá exportar la lista. 
darle un ID de operacion  debe estar cordinado con el feature de Usuarios, Roles y privilegios 

Debes agregar logs 
que usuario exporto la lista y los detalles del contenido;
numero de tickets filtrados.

2024-08-31 06:01 UTC, julianMondragon requested changes
Leave my comments @DulceAPTS but also Github say that you neet check out your branch because has conflicts that must be resolved on Controllers/TicketsController.cs

2024-09-03 16:49 UTC, DulceAPTS commented on Models/ViewModel/TicketViewModel.cs
>          public List<CurrentList2> CurrentList2 { get; set; }
Sí, se usa para los filtros, ya lo borré del ViewModel y me salen errores en TicketsController y el IndexWithFilter.

2024-09-03 16:50 UTC, DulceAPTS commented on Controllers/TicketsController.cs
> +            // Construye el nombre del archivo sin repetir ".xlsx"
✅

2024-09-04 18:35 UTC, DulceAPTS commented on Controllers/TicketsController.cs
> +            if (!Directory.Exists(savePath))
Se resolvió con stream, guardando el archivo en memoria en vez de en el servidor

2024-09-04 18:44 UTC, DulceAPTS commented
INSERT INTO [dbo].[Operacion] (nombre, id_Modulo)
VALUES ('Exportar_Tickets', 1);

INSERT INTO [dbo].[Roll_Operacion] (id_Roll, id_Operacion)
VALUES ('1', 40);

INSERT INTO [dbo].[Roll_Operacion] (id_Roll, id_Operacion)
VALUES ('2', 40);

Para hacer pruebas pueden agregar estas nuevas filas en la bd

2024-09-04 20:01 UTC, Brenda-byte approved these changes
Nota: en el Id de operacion para probar se requiere ajustar de acuerdo al tamaño de la tabla de la base de datos y en la parte de exporttableticket controller para poder validar.
Ejemplo cambie del 40 al 23 

INSERT INTO [dbo].[Operacion] (nombre, id_Modulo)
VALUES ('Exportar_Tickets', 1);

INSERT INTO [dbo].[Roll_Operacion] (id_Roll, id_Operacion)
VALUES ('1', 23);

INSERT INTO [dbo].[Roll_Operacion] (id_Roll, id_Operacion)
VALUES ('2', 23);

Para Visual studio se modifica en esta parte
 [AuthorizeUser(idOperacion: 23)]

2024-09-04 20:11 UTC, AbrahamGS13 approved these changes
al momento de abrir el excel, no se tiene una interpretación buena de las dos pantallas, no es fácil tener una conclusión correcta para el uso de las dos pantallas

2024-09-18 06:55 UTC, julianMondragon approved these changes
ok.

2024-09-18 06:56 UTC, merged