Se ha cambiado la fuente de la página de inicio
julianMondragon/TAS360 pull request #45
Opened 2024-10-13 16:46 UTC by DulceAPTS

Se cambió la fuente de la página de inicio a fuentes según el manual de identidad.

2024-10-14 22:37 UTC, julianMondragon requested changes
La pestaña de SLA no se apega al formato de las demás pestañas 
 
![image](https://github.com/user-attachments/assets/bc1d1368-45cf-4cfc-8f26-a124fe36d50f)

aqui mismo en esta pestaña favor se subir el contenido que esta al final de pagina (la descripción de SLA) entre el titulo y las primeras graficas.

2024-10-22 20:10 UTC, RasAzarim commented
Se observa funcionando de forma adecuada

2024-10-24 16:33 UTC, RasAzarim reviewed
Se observa funcionando de forma correcta

2024-10-28 15:52 UTC, AbrahamGS13 approved these changes
Funcionamiento correcto.

2024-10-31 01:31 UTC, julianMondragon approved these changes
Ok, godjob.

2024-10-31 01:31 UTC, merged