Se agrega la columna Roll en los metodos crear y editar usuario
julianMondragon/TAS360 pull request #48
Opened 2024-10-21 16:30 UTC by emilianogp23

Se agrega la columna Roll en la vista de crear y editar usuario. 

Se modifico el controlador  "User controller", el view model "Listusuarioviewmodel" y la vista de crear y editar usuario.  

Se hace referencia al feature: Agregar columna -RolI al método “Crear, editar Usuario “
[#19](https://github.com/julianMondragon/TAS360/issues/19)

2024-10-21 18:41 UTC, DulceAPTS requested changes
Fue probada la nueva funcionalidad. Se puede crear el nuevo usuario con el rol que se seleccione y aparece correctamente en la columna rol de la bd, pero al editar a un usuario existente no se modifica el rol en la tabla User, sigue permaneciendo el rol con el que fue creado aún si lo modifica un usuario con rol de administrador.

2024-10-22 01:45 UTC, emilianogp23 commented
Se corrige el Bug de guardado de rol al editar usuario agregando la linea " userToEdit.id_Roll = model.Rolid;" dentro de el controlador para que realice el guardado.

2024-10-22 23:05 UTC, RasAzarim commented
Se revisa la funcionalidad se observa que realiza el cambio de roll, cuando se trata de realizar el cambio de roll sin modificar la contraseña, no permite el cambio hasta que se agrega la contraseña del usuario nuevamente
![evidencia_Columna_Roll_1](https://github.com/user-attachments/assets/0e522576-b128-4c49-a2a2-cd5009084741)
![evidencia_Columna_Roll_2](https://github.com/user-attachments/assets/1983d3fd-4af1-498c-a250-fb06530edccd)
![evidencia_Columna_Roll_3](https://github.com/user-attachments/assets/1e7abb23-208c-4413-b421-5b991d320913)

2024-10-24 16:58 UTC, RasAzarim reviewed
Se realizan pruebas, se observa que el cambio de roll se realiza correctamente sin embargo al tratar de guardar los cambios sin actualizar el password es donde se observa el problema ya que se observa no recupera el valor anterior del password para conservarlo, se agregan capturas para mostrar lo antes mencionado
-Cambio de roll sin password
![evidencia_Columna_Roll_1](https://github.com/user-attachments/assets/5ca56f24-94f1-47a0-ab8d-edc53df674ad)
-Resultado de intento de guardar
![evidencia_Columna_Roll_2](https://github.com/user-attachments/assets/22f53c5d-66e5-4594-b2e0-89462d35d360)
-Vista de  la base de datos antes del cambio con el password
![evidencia_Columna_Roll_3](https://github.com/user-attachments/assets/ce953487-648c-4d85-9ddd-271f22e93453)
-cambio de roll con password
![evidencia_Columna_Roll_4](https://github.com/user-attachments/assets/cb0ebf9a-0e97-40ad-a832-fed2c639bbf3)
-Vista de  la base de datos despues del cambio con el password
![evidencia_Columna_Roll_5](https://github.com/user-attachments/assets/f324e14a-4714-4797-90cf-1b77d56cc810)

2024-10-28 16:45 UTC, RasAzarim reviewed
Se revisa la funcionalidad, se observa que funciona de forma correcta

2024-10-31 01:16 UTC, julianMondragon commented on Controllers/UserController.cs
> +
TODO:
Remover lineas comentadas.

2024-10-31 01:21 UTC, julianMondragon approved these changes

2024-10-31 01:23 UTC, emilianogp23 commented on Controllers/UserController.cs
> +
Okay, se agregara la tarea

2024-10-31 05:47 UTC, DulceAPTS approved these changes
Se ve bien

2024-10-31 17:44 UTC, Brenda-byte approved these changes
👍

2024-11-02 02:05 UTC, merged