43 bug envia emails
julianMondragon/TAS360 pull request #50
Opened 2024-10-21 17:06 UTC by AbrahamGS13

Al momento de editar el ticket, se debe de enviar un correo notificando los cambios de este, de la misma manera al agregar un comentario al mismo ticket, notificación será de la misma manera: 

El ticket ??? ha sido actualizado. A continuación se muestran los detalles:
Título: Título del ticket
Estado: Status del ticket
Último Comentario: Texto en el campo del reporte.

Al momento de agregar comentario se envía el correo de la misma manera, el bug causaba que el se mandaba el primer comentario del ticket, sin tomar en cuenta el texto del reporte. El formato será de la siguiente manera:

El ticket ??? ha sido actualizado. A continuación se muestran los detalles:
Título: Título del ticket
Estado: Status del ticket
Último Comentario: ****************** * Cambio de Status a: ??????******************Comentario agregado

2024-10-21 20:09 UTC, DulceAPTS requested changes
Fue probada la correción del bug. El archivo Web.config lo subiste modificado apuntando a tu repositorio local, hay que revertir ese cambio. 
El correo que se envió al agregar el nuevo comentario está desordenado.
![image](https://github.com/user-attachments/assets/3c9f3db4-dfd1-4764-88ae-4061b3cab209)
Aparece de esta forma:

Estado: Correccion
Último Comentario: ***************************************************** * Cambio de Status a:Correccion ***************************************************** Último comentario del ticket prueba

No creo que sea necesario poner "Cambio de Status a:" ya que el último estatus ya se muestra en "Estado:", y en la parte de "Último Comentario: " aparece ******* en vez del último comentario con el que probé "Último comentario del ticket prueba" que aparece al final de todo el texto.

2024-10-22 00:11 UTC, julianMondragon commented
> No creo que sea necesario poner "Cambio de Status a:" ya que el último estatus ya se muestra en "Estado:", y en la parte de "Último Comentario: " aparece ******* en vez del último comentario con el que probé "Último comentario del ticket prueba" que aparece al final de todo el texto.

Me parece una excelente observación, lo que se muestra en el correo es el contenido del ultimo comentario asignado a este ticket y en este caso cambio de estatus por lo cual al crearse el comentario el sistema le agrega dicho contenido innecesario. 

Esto nos deja con la variante de que sucederá en ciertos casos nadamas, como lo solucionaría usted. 
@DulceAPTS  

cadete @AbrahamGS13  debe atender el comentario antes de que se apruebe este PR.

2024-10-24 17:38 UTC, RasAzarim reviewed
Se observa que se reciben los correos al momento de agregar un comentario o de editar, mas al momento de agregar un segundo comentario el correo no llega se anexan evidencias 
-Correo Recibido después agregar comentario 
![evidencia_Correo_1](https://github.com/user-attachments/assets/d69728cb-3cfe-4df1-8c07-af7bae387477)
-Se agrega segundo comentario con horas 
![evidencia_Correo_2](https://github.com/user-attachments/assets/2a2a61d2-bddc-4c90-9f5c-0164d6d0bcaa)
-Bandeja de correo después de agregar comentarios donde se observa que el ultimo correo recibido es el del comentario de 10:13 am
![evidencia_Correo_3](https://github.com/user-attachments/assets/16a79629-1bc2-43bd-8cbe-47f530650c1e)

2024-10-24 20:38 UTC, AbrahamGS13 commented
solvente el bug, solicito una nueva revisión 
@RasAzarim 
@DulceAPTS 
@emilianogp23 
@Brenda-byte 
@julianMondragon

2024-10-28 17:08 UTC, RasAzarim reviewed
Se revisa la funcionalidad, se observa que funciona de forma correcta

2024-10-31 01:05 UTC, julianMondragon approved these changes
Este commit tiene los cambios del web config apuntando a producción. 
Dejare que esto se suba a si derivado de la baja que tenemos del cadete Abraham. 
Se corregirá en un fixbug en el sprint 5

2024-10-31 05:47 UTC, DulceAPTS approved these changes
👍

2024-10-31 17:42 UTC, Brenda-byte approved these changes
👍

2024-11-02 02:04 UTC, merged